version: '3.4'

#Драйвер "bridge" создает виртуальную сеть между контейнерами и позволяет им общаться друг с другом, а также предоставляет контейнерам доступ к внешним сетевым ресурсам.

networks:
  dev:
    driver: bridge

#"image" указывает Docker-образ, который должен быть использован для запуска контейнера сервиса "bigproject". В данном случае, используется образ "docker.io/library/bigproject".

#"depends_on" определяет зависимости сервиса от другого сервиса в приложении. Здесь "bigproject" зависит от сервиса "app_db".

#"container_name" задает имя контейнера для сервиса "bigproject".

#"ports" указывает на проброс портов из контейнера в хост-систему. В данном случае, порт 80 в контейнере "bigproject" будет проброшен на порт 8088 на хост-системе.

#"build" определяет контекст сборки и Dockerfile для построения Docker-образа. Здесь используется Dockerfile, находящийся в текущем контексте.

#"environment" определяет переменные среды для сервиса

#"networks" задает имя сети для контейнера сервиса

#restart always указывает на то, что контейнер должен перезапускаться при его остановке.

#volumes используются для сохранения данных вне жизненного цикла контейнера, а также позволяют обмениваться данными между контейнерами и хост-машиной.


services:
  web-api:
    depends_on:
      - "postgres"
    container_name: web-api
    ports:
      - "8088:80"
    build:
      context: ./BigProject
      dockerfile: Dockerfile
    environment:
      - DefaultConnection=Server=postgres;Port=5432;Database=BigProjectDb;User ID=postgres;Password=postgres;IntegratedSecurity=true;Pooling=true;
    networks:
      - dev
  front-end:
    container_name: front-end
    build:
      context: ./react-app
      dockerfile: Dockerfile
    ports:
      - "8089:3000"
    volumes:
      - ./react-app:/app

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=BigProjectDb
    restart: always
    volumes:
      - ./BigProject/app_data:/var/lib/postgresql/data
    networks:
      - dev