version: '3.4'

#Драйвер "bridge" создает виртуальную сеть между контейнерами и позволяет им общаться друг с другом, а также предоставляет контейнерам доступ к внешним сетевым ресурсам.

networks:
  dev:
    driver: bridge

#"image" указывает Docker-образ, который должен быть использован для запуска контейнера сервиса "bigproject". В данном случае, используется образ "docker.io/library/bigproject".

#"depends_on" определяет зависимости сервиса от другого сервиса в приложении. Здесь "bigproject" зависит от сервиса "app_db".

#"container_name" задает имя контейнера для сервиса "bigproject".

#"ports" указывает на проброс портов из контейнера в хост-систему. В данном случае, порт 80 в контейнере "bigproject" будет проброшен на порт 8088 на хост-системе.

#"build" определяет контекст сборки и Dockerfile для построения Docker-образа. Здесь используется Dockerfile, находящийся в текущем контексте.

#"environment" определяет переменные среды для сервиса

#"networks" задает имя сети для контейнера сервиса

#restart always указывает на то, что контейнер должен перезапускаться при его остановке.

#volumes используются для сохранения данных вне жизненного цикла контейнера, а также позволяют обмениваться данными между контейнерами и хост-машиной.


services:
  bigproject:
    image: docker.io/library/bigproject
    depends_on:
        - "app_db"
    container_name: bigproject-services
    ports:
        - "8088:80"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
        - ConnectionStrings__DefaultConnection=User ID=postgres;Password=postgres;Server=app_db;Port=5432;Database=BigProjectDriver; IntegratedSecurity=true;Pooling=true;
        - ASPNETCORE_URLS=http://+:80
    networks:
        - dev

  app_db:
     image: postgres:latest
     container_name: app_db
     environment:
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=postgres
         - POSTGRES_DB=BigProjectDriver
     ports:
         - "5433:5432"
     restart: always 
     volumes:
         - app_data:/var/lib/postgresql/data
     networks:
         - dev
volumes:
    app_data: